### ISSUE TITLE
Dataset size & finetuning code

### ISSUE THREAD

**Issue by C00reNUT** [viitor-ai/viitor-voice#1]
Hello,

thank you for making this public, nice results considering the model size, may I ask you:

1.) How many hours of audio were in the dataset you used for training?

2.) Do you plan to release training/finetuning code?

Thank you!

**Comment by MrWaterZhou** [comment]
> Hello,
> 
> thank you for making this public, nice results considering the model size, may I ask you:
> 
> 1.) How many hours of audio were in the dataset you used for training?
> 
> 2.) Do you plan to release training/finetuning code?
> 
> Thank you!

Thanks for showing interest in our open-source project!

1) The open-source version of the model uses only open-source datasets, and detailed information has been specified in the model tags on Hugging Face(https://huggingface.co/ZzWater/viitor-voice-en).
2) Yes, we are currently organizing the code and will open-source the data processing and training code in the near future.
